spring:
  config:
    import:
    - config.yml
    - datasource.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gcp.connect.psdb.cloud/redblue?sslMode=VERIFY_IDENTITY #planetScale
    #username, password > datasource.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        #format_sql: true

logging:
  level:
    org:
      springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: off
