spring:
  datasource:
    url: jdbc:mysql://gcp.connect.psdb.cloud:3306/redblue?useUnicode=true&serverTimezone=Asia/Seoul
    username: lx8zcrtiiibne12kqbiv
    password: pscale_pw_x46pvkl0CXU4qrSNBwhjoKSqiVAa9tdPfqqy3YUlLD8
    driver-class-name: com.mysql.cj.jdbc.Driver